### ISSUE TITLE
no response to any key

### ISSUE THREAD

**Issue by lh8511** [ma1co/PMCADemo#1]
Hello,
In advance lets congrat you for this good job.
I did upload your demo to my nex6 camera, but after initialization it not responde to any camera keys functions...
I also downloaded some sony apps, check their code and some could be patched in easy way, however would be nice to test/debug before install it on camera.
Regards

**Comment by ma1co** [comment]
Does the trash key work? (it should exit the app)

**Comment by lh8511** [comment]
No. 
Once you enter the app and choose an item, no way to go back or exit the app on good way.
I believe is some behavior of Nex6, since some sony apps have routines for a good use of   the trash key... 
Anyaway is not relevant how to exit your demo app.

**Comment by ma1co** [comment]
Maybe it's just the key mapping...
Have you tried the "key events" item? Which key events show?

**Comment by ma1co** [comment]
Can you try version 0.4 (just reinstall the app)? Which key events show?

**Comment by lh8511** [comment]
ok, I will try as soon can power charge the camera.
Thank you

**Comment by lh8511** [comment]
Installed version 0.4
At key events item (on my nex6):
the 'trash key" returned this log "Unknown key pressed: 0/513"...
The 'menu key' returned this log Unknown key pressed: 82/229"

note: all other keys got the correct response on log key event!

**Comment by ma1co** [comment]
should be fixed in v0.5

**Comment by lh8511** [comment]
Now it works well. Thanks
