### ISSUE TITLE
Autoload app after camera reset

### ISSUE THREAD

**Issue by volzotan** [ma1co/PMCADemo#10]
The apps distributed via the PlayMemories Store are loaded right after the camera is started and need to be killed explicitely.
The Demo app is not automatically loaded after powerup. Any idea what needs to be done to change that behaviour?

**Comment by obs1dium** [comment]
I've been looking into that as well, but no luck so far.

Not all Sony apps display this behavior, so in theory it should be possible to find out how they do it by comparing two such apps. Unfortunately their code is anything but straightforward...

**Comment by volzotan** [comment]
I've tried that but had no luck so far. There is a mysterious bootId, but that may only be a weird named variable. Only thing I can tell is that whatever the app does to tell the android os to reload it after a restart may happen on shutdown. 
(If you do a hard shutdown and not turn it off via the on/off-switch, i.e. remove battery, the timelapse app is not loaded after startup)

**Comment by obs1dium** [comment]
I just had another look and found out how to do it.
Have a look at BaseActivity.java:
```java
protected void notifyAppInfo() {
    Intent intent = new Intent("com.android.server.DAConnectionManagerService.AppInfoReceive");
    intent.putExtra("package_name", getComponentName().getPackageName());
    intent.putExtra("class_name", getComponentName().getClassName());
    //intent.putExtra("pkey", new String[] {});// either this or these two:
    //intent.putExtra("pullingback_key", new String[] {});
    //intent.putExtra("resume_key", new String[] {});
    sendBroadcast(intent);
}
```
The `pullingback_key` defines when to exit the app. If you want the app to exit when a USB cable is plugged in, use
```java
intent.putExtra("pullingback_key", new String[] { "KEY_USB_CONNECT" });
```
I think the `resumekey` specifies after which power-off events the app should be resumed. 
```java
public static final String KEY_ACCESSORY_APO = "KEY_ACCESSORY_APO";
public static final String KEY_DEDICATED_APO = "KEY_DEDICATED_APO";
public static final String KEY_LENS_APO = "KEY_LENS_APO";
public static final String KEY_MEDIA_INOUT_APO = "KEY_MEDIA_INOUT_APO";
public static final String KEY_PLAY_APO = "KEY_PLAY_APO";
public static final String KEY_PLAY_PON = "KEY_PLAY_PON";
public static final String KEY_POWER_APO = "KEY_POWER_APO";
public static final String KEY_POWER_SLIDE_PON = "KEY_POWER_SLIDE_PON";
public static final String KEY_RELEASE_APO = "KEY_RELEASE_APO";
...
intent.putExtra("resume_key", new String[] {KEY_POWER_SLIDE_PON, KEY_RELEASE_APO, KEY_PLAY_APO, KEY_MEDIA_INOUT_APO, KEY_LENS_APO, KEY_ACCESSORY_APO, KEY_DEDICATED_APO, KEY_POWER_APO, KEY_PLAY_PON});
```
There are other keys ("small_category", "large_category"), but I don't know what their use is.

**Comment by volzotan** [comment]
Tested it and can confirm that this solves exactly the problem. Thanks a lot for sharing!
