### ISSUE TITLE
Compiling and finally installing PMCADemo

### ISSUE THREAD

**Issue by AndyZuerich** [ma1co/PMCADemo#11]
Hi,

I'd like to use PMCA Demo for my own application as template. Now I have a problem: I can download and install Apps that are ready and prepared. And, I managed to compile PMCADemo on my linux computer. However, I cannot install my own compiled program onto the camera. After fiddling around for a (long!) while, I found that the signing-procedure is probably the issue.

The error message that I always receive from the pmca-gui.py app was quite confusing:

```
Traceback (most recent call last):
  File "./pmca-gui.py", line 76, in do
    installCommand(None, None, f)
  File "/home/andy/SonyNex/Sony-PMCA-RE/pmca/commands/usb.py", line 224, in installCommand
    installApp(device, host, apkFile, appPackage, outFile)
  File "/home/andy/SonyNex/Sony-PMCA-RE/pmca/commands/usb.py", line 72, in installApp
    raise Exception('Communication error %d: %s' % (result.code, result.message))
Exception: Communication error 100: Error completed

```

In case I use the original PMCADemo.apk file, it works to install onto the camera. When I re-sign the original apk-file, then I get the same error message as above. Is there any special thing that I need to consider when signing the apk?

Any hints would be a great help.

A short comment on what I intend to do: I would like to write a script that allows me an accurate timing with many different shutter settings for photographing the solar eclipse in August in USA.

**Comment by ma1co** [comment]
You cannot reinstall / update an Android app if the signature has changed. Uninstall PMCADemo or change the application id of your app to resolve the issue.

**Comment by AndyZuerich** [comment]
You saved my day, thanks a lot! Now, I could install my (or better: your) app. In case my experiments give some good outcome, I will publish my code.
Just for information: For Canon/Nikon cameras, there is a PC software available called "EclipseOrchestrator", which controls the camera to generate hundreds of raw images with pre-defined iso's and shutter speed settings. I plan to have something similar (if at all possible) integrated into the camera.
Thanks again for your advice (I am good in Java, but this is actually one of my first Android projects).
