### ISSUE TITLE
Customized app installing error

### ISSUE THREAD

**Issue by gabo-alvarez** [ma1co/PMCADemo#13]
I have the following error when I try to install a new app based on the PMCADemo. 

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Querying MTP device
Sony Corporation ILCE-6500 is a camera in app install mode
Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Traceback (most recent call last):
File "C:\projects\sony-pmca-re\pmca-gui.py", line 77, in do
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 256, in installCommand
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 76, in installApp
Exception: Communication error 100: Error Completed

I've already had  similar problems when installing another app (issue #42), the error code was the same (Communication error 100) BUT error lines were not the same . Last one was on line 76 in do ( pmca-gui.py) and line 224 in installCommand (usb.py). This time lines are different as you can see. AND , most importantly , I already tried the solutions that worked for me the last time: 
The reason of the bug last time was a dupplicate appId, so I unistalled old apps with the same id and it worked. This time I tried that also and I  changed the appId in  my app too. Even with that is not working this time, so I think its a different error.  I'm working with the v0.16 version. The camera is a Sony a6500

**Comment by ma1co** [comment]
Please download the newest version of pmca-gui (v0.17) and try again. It should print more infos about the apk file. Please post the output.

**Comment by ssh4net** [comment]
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6500 is a camera in app install mode

Analyzing apk

Package: com.gabdev.ebracket
Version: 1.5
Warning: Cannot read apk certificate

Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 79, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 291, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 86, in installApp
Exception: Communication error 100: Error completed

**Comment by gabo-alvarez** [comment]
That's the error log after updating to v0.17. Something I didn't mention before, I'm developing in a new PC, different from the PC in which I compiled the old app that worked.

**Comment by ma1co** [comment]
According to the warning, the apk is not signed. Make sure to at least sign it with a developer certificate.

**Comment by gabo-alvarez** [comment]
It's signed with a developer certificate. In fact , we  tried installing the same app but this time unsigned and it worked

**Comment by ma1co** [comment]
I'll consider this as resolved. Feel free to reopen.
