### ISSUE TITLE
Unable to compile sample

### ISSUE THREAD

**Issue by Boldbrew** [ma1co/PMCADemo#8]
Could sombody help me with compilation?
I'm getting the following error during gradle build:

  35         textView = (TextView) findViewById(R.id.logView);
  36 
  37         wifiManager = (WifiManager) getSystemService(Context.WIFI_SERVICE);
  38         wifiDirectManager = (DirectManager) getSystemService(DirectManager.WIFI_DIRECT_SERVICE);

  39 
  40         wifiStateReceiver = new BroadcastReceiver() {

**Comment by ma1co** [comment]
Add this to the `onCreate` declaration:

```
@android.annotation.SuppressLint("WrongConstant")
```

**Comment by Boldbrew** [comment]
Solved

**Comment by altendky** [comment]
I had the same error.  Should this be added into the source or are @Boldbrew and I setting something up wrong?
